name: Publish 'xpu' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Monday, 07:00 UTC
    - cron: '0 7 * * 1'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!xpu/Dockerfile'
      - '!xpu/builder-scripts/**'
      - '!xpu/runner-scripts/**'
      - '!.github/workflows/build-xpu.yml'

jobs:

  build-publish-xpu:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      -
        name: Git checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build 'xpu'
        uses: docker/build-push-action@v6
        with:
          context: ./xpu
          file: ./xpu/Dockerfile
          tags: |
            yanwk/comfyui-boot:xpu
            yanwk/comfyui-boot:xpu-${{ steps.date.outputs.date }}
          load: true
      - 
        name: Test 'xpu'
        run: |
          docker run --rm \
            --name comfyui-quick-test \
            -e CLI_ARGS="--quick-test-for-ci --cpu" \
            yanwk/comfyui-boot:xpu-${{ steps.date.outputs.date }}
      -
        name: Push 'xpu'
        uses: docker/build-push-action@v6
        with:
          context: ./xpu
          file: ./xpu/Dockerfile
          tags: |
            yanwk/comfyui-boot:xpu
            yanwk/comfyui-boot:xpu-${{ steps.date.outputs.date }}
          push: true
