name: Publish 'xpu-cn' to Docker Hub

on: 
  workflow_dispatch: # 可以手动触发
  schedule: # 每周一 07:00 UTC 自动运行
    - cron: '0 7 * * 1'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!xpu-cn/Dockerfile'
      - '!xpu-cn/builder-scripts/**'
      - '!xpu-cn/runner-scripts/**'
      - '!.github/workflows/build-xpu-cn.yml'

jobs:

  build-publish-xpu-cn:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          # overprovision-lvm: 'true'
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          swap-size-mb: 512
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Git checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build 'xpu-cn'
        uses: docker/build-push-action@v6
        with:
          context: ./xpu-cn
          file: ./xpu-cn/Dockerfile
          build-args: |
            USING_GITHUB_ACTIONS=true
          tags: |
            yanwk/comfyui-boot:xpu-cn
            yanwk/comfyui-boot:xpu-cn-${{ steps.date.outputs.date }}
          load: true
      - 
        name: Test 'xpu-cn'
        run: |
          docker run --rm \
            --name comfyui-quick-test \
            -e CLI_ARGS="--quick-test-for-ci --cpu" \
            yanwk/comfyui-boot:xpu-cn-${{ steps.date.outputs.date }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Push 'xpu-cn'
        uses: docker/build-push-action@v6
        with:
          context: ./xpu-cn
          file: ./xpu-cn/Dockerfile
          build-args: |
            USING_GITHUB_ACTIONS=true
          tags: |
            yanwk/comfyui-boot:xpu-cn
            yanwk/comfyui-boot:xpu-cn-${{ steps.date.outputs.date }}
          push: true
