name: Publish 'xpu' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered

jobs:

  build-publish-xpu:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          swap-size-mb: 512
      -
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'xpu'
        uses: docker/build-push-action@v6
        with:
          context: ./xpu
          file: ./xpu/Dockerfile
          tags: |
            yanwk/comfyui-boot:xpu
            yanwk/comfyui-boot:xpu-${{ steps.date.outputs.date }}
          push: true
